<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PAYLITY Receipt — {{ $receipt['reference'] }}</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color: #0f172a; margin: 24px; }
        .brand { font-size: 22px; font-weight: 800; color: #0b2d5c; }
        .subtitle { font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase; color: #64748b; }
        .section { margin-top: 20px; }
        .section h3 { font-size: 11px; text-transform: uppercase; color: #64748b; margin-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 6px 0; font-size: 13px; }
        td.label { color: #64748b; width: 45%; }
        td.value { text-align: right; font-weight: 600; }
        .total { border-top: 1px solid #e2e8f0; padding-top: 8px; font-size: 15px; font-weight: 800; }
        .qr { margin-top: 24px; text-align: center; }
        .verify { margin-top: 8px; font-size: 11px; color: #64748b; word-break: break-all; }
        .footer { margin-top: 28px; font-size: 11px; color: #64748b; }
    </style>
</head>
<body>
    <div class="brand">PAYLITY NG</div>
    <div class="subtitle">Transaction Receipt</div>
    <p style="font-family: monospace; font-weight: 700;">{{ $receipt['reference'] }}</p>

    <div class="section">
        <h3>Transaction</h3>
        <table>
            <tr><td class="label">Reference</td><td class="value">{{ $receipt['reference'] }}</td></tr>
            <tr><td class="label">Product</td><td class="value">{{ $receipt['product_label'] }}</td></tr>
            <tr><td class="label">Timestamp</td><td class="value">{{ $receipt['timestamp'] }}</td></tr>
        </table>
    </div>

    <div class="section">
        <h3>Customer</h3>
        <table>
            <tr><td class="label">Phone</td><td class="value">{{ $receipt['customer_phone'] }}</td></tr>
        </table>
    </div>

    <div class="section">
        <h3>Charges</h3>
        <table>
            <tr><td class="label">Product Amount</td><td class="value">₦{{ number_format($receipt['product_amount'], 2) }}</td></tr>
            <tr><td class="label">Convenience Fee</td><td class="value">₦{{ number_format($receipt['convenience_fee'], 2) }}</td></tr>
            <tr><td class="label">Gateway Charge</td><td class="value">₦{{ number_format($receipt['gateway_fee'], 2) }}</td></tr>
            <tr class="total"><td class="label">Total Paid</td><td class="value">₦{{ number_format($receipt['payable_amount'], 2) }}</td></tr>
        </table>
    </div>

    <div class="section">
        <h3>Status</h3>
        <table>
            <tr><td class="label">Payment</td><td class="value">{{ $receipt['payment_status'] }}</td></tr>
            <tr><td class="label">Fulfillment</td><td class="value">{{ $receipt['fulfillment_status'] }}</td></tr>
            @if(!empty($receipt['failure_reason']))
            <tr><td class="label">Failure Reason</td><td class="value">{{ $receipt['failure_reason'] }}</td></tr>
            @endif
            @if(!empty($receipt['fulfillment_reference']))
            <tr><td class="label">Fulfillment Ref</td><td class="value">{{ $receipt['fulfillment_reference'] }}</td></tr>
            @endif
        </table>
    </div>

    <div class="qr">
        <img src="{{ $qrCodeDataUri }}" alt="Verification QR code" width="120" height="120">
        <div class="verify">Verify: {{ $receipt['verification_url'] }}</div>
    </div>

    <div class="footer">Generated by PAYLITY NG. Verify authenticity using the QR code or URL above.</div>
</body>
</html>
